### ISSUE TITLE
Update latest version to pip

### ISSUE THREAD

**Issue by stephantul** [pettarin/ipapy#3]
Hi Alberto,

Thanks for making this great package.

Would it be possible to upload the latest version (with the fix from #2 ) to pip? 
We use ipapy within [wordkit](https://www.github.com/clips/wordkit). Apparently Windows users have problems installing this due to this encoding issue.

If not, then I'll add a work-around to Wordkit.

Thanks!
Stéphan

**Comment by pettarin** [comment]
@stephantul I think I missed the notification for this issue... anyhow you should be able to pick v0.0.9 from PyPI now.

**Comment by pettarin** [comment]
@stephantul  @BramVanroy  Two notes:

1. I do not have a personal Windows box to test, so Windows support is "best effort"
2. next time, please shoot me an email if you do not hear from me in say 2 weeks

Note that I slightly changed @BramVanroy fix, using ``import io``, which works for both Python 2.x and 3.x

**Comment by stephantul** [comment]
Great, thanks so much! I have access to a Windows box, I'll let you know if it works.

**Comment by pettarin** [comment]
I tried, and it works on Windows, including the CLI tool.
